### ISSUE TITLE
[FEEDBACK] Question about TabCenterReborn and huge thanks you

### ISSUE THREAD

**Issue by Froggy232** [largestgithubuseronearth/addwater#11]
Hi,
First, please let me write an huge thanks you for your app, I use the flatpak version of Firefox on Fedora Silverblue with Gnome Theme for Firefox, and was maintining it manually until you made your app, it's really nice I think and will help to integrate firefox into gnome for a lot of user!
I have a question about TabCenterReborn, do you support it?
Also, if I add some experimental features in my user.js files, will they stay after upgrades or be reinitialised?
Thanks you a lot anyway, it's a really nice soft, I will also try to find answer to theses questions by trying the app directly this afternoon.
Have a nice day, and thanks again!

**Comment by largestgithubuseronearth** [comment]
I don't support TCR at the moment but I intend to in the near future. 

There was a bug which meant user.js changes would be overwritten but it will be fixed soon so your changes to the user.js will stay between installs. So you'll be able to enable the theme's TCR support manually.

Thank you very much for your nice words. I hope you find it useful.

**Comment by Froggy232** [comment]
Hi again,
It's very good news, I will just wait for theses changes to land and keep a look on this project then.
Thanks you again, it's indeed very, very useful to me (and I'm sure to a lot of other.). Thanks you a last time, for your answer and your work!
Have a very nice day

**Comment by largestgithubuseronearth** [comment]
The user.js fixes have been landed in Flathub so you'll be safe to add your experimental changes. I'll take a look at supporting TCR in the next couple weeks, once some of the current major bugs are sorted out.

Thanks again for your feedback. I hope you enjoy using the app.
