### ISSUE TITLE
do not overwrite the user.js

### ISSUE THREAD

**Issue by TheRsKing** [largestgithubuseronearth/addwater#12]
**Describe the bug**
when a change is made, the entire user.js is overwritten. this has its disadvantages when using hardening such as betterfox etc.

**To Reproduce**
1. apply a custom user.js
2. load the app and change something
3. see how the user.js gets overwritten

**Expected behavior**
instead of overwriting the content, simply make the changes and append them as it is done with the official curl script

**Please include the log file from the day it happened**
Don't think there are any logs needed here, if there are, just ask me :)

**Technical Details (please complete the following information):**
 - Distribution: Aeon Desktop
 - Add Water version: rc1.1

 - Browser: Firefox
 - Browser Package: Flatpak
 - Browser Version: 131.0.3

**Comment by gxanshu** [comment]
@largestgithubuseronearth i want to fix, will create a PR :v

**Comment by TheRsKing** [comment]
> I was also having the same issue, i fixed and created a PR at #13 

Amazing 🙏

**Comment by largestgithubuseronearth** [comment]
Thank you for reporting this. My mistake. 

Pushing the changes to Flathub in a moment.

**Comment by largestgithubuseronearth** [comment]
The update should appear on Flathub within a few hours. Closing this now but please open another issue if the problem persists after updating the app.

**Comment by TheRsKing** [comment]
![grafik](https://github.com/user-attachments/assets/3a5fc49e-a312-41d3-a8b7-c17bc51c683b)
great it works. Also thanks for this very good app :)
