### ISSUE TITLE
no support for firefox flatpak

### ISSUE THREAD

**Issue by notHaider** [largestgithubuseronearth/addwater#16]
**Describe the bug**
applying the theme using the app doesnt work for firefox flatpak installationgs

**To Reproduce**
1. select desired settings 
2. save it
3. start/ restart firefox
4. no profit

**Expected behavior**
i assumed that because the app is on flathub it would work with the firefox version from the same s

**Please include the log file from the day it happened**
You can find this in: [About Add Water > Report an Issue]
didnt find it :(

**Screenshots**
nop 

**Technical Details (please complete the following information):**
 - Distribution: opensuse tumbleweed and firefox flatpak from flathub
 - Add Water version: rc1.1

 - Browser: Firefox
 - Browser Package: flatpak 
 - Browser Version: 131.0.3

**Comment by notHaider** [comment]
i just saw the issue created beffore me

**Comment by largestgithubuseronearth** [comment]
Do you also have any other package format of Firefox installed at the moment? I'm working on a fix for the other issue.

**Comment by largestgithubuseronearth** [comment]
If you don't, then the issue might be caused by something else.
