### ISSUE TITLE
[FEATURE REQUEST] Please add support for new v132 options

### ISSUE THREAD

**Issue by NotoriousNico** [largestgithubuseronearth/addwater#28]
[Firefox GNOME Theme v132](https://github.com/rafaelmardojai/firefox-gnome-theme/releases/tag/v132) comes with two new options:

`gnomeTheme.allTabsButton`
**Show the _List All Tabs_ button all the time, like stock Firefox.**

`gnomeTheme.tabAlignLeft`
**Align the tab title and favicon to left of tab in place of center.**

These options are currently not present in Add Water.
Could you please add them, if you find the time?

**Comment by largestgithubuseronearth** [comment]
Sure. I'll look into sending an update by the end of the day.

**Comment by largestgithubuseronearth** [comment]
The new options will come in a few hours in v1.1.6. Let me know if there's anything else I can do.

I hoped to include the tab overflow preference but that isn't possible at the moment. Still, I hope this helps.

Thanks for letting me know.

**Comment by NotoriousNico** [comment]
That was fast, thank you so much for adding those two options.
Will test the new version as soon as it comes out.

Thanks again!
