### ISSUE TITLE
[FEATURE REQUEST] Move bars to bottom

### ISSUE THREAD

**Issue by mburucuyapy** [largestgithubuseronearth/addwater#30]
Any chance to have the option to move the tabs and the address bar to the bottom of the display? This will be a bit more comfortable on tablets and other mobile devices.

**Comment by largestgithubuseronearth** [comment]
A good question but you'd be better served asking the upstream theme developer. I only provide the app to automatically install the theme. He does all the real work for the theme and the options it supports.

https://github.com/rafaelmardojai/firefox-gnome-theme
