### ISSUE TITLE
[FEATURE REQUEST] Support for gnome 47 accent colors

### ISSUE THREAD

**Issue by Blisterexe** [largestgithubuseronearth/addwater#33]
**What is the issue you're having?**
What are you doing when you wish this feature exists? What is the root problem it solves?

Currently, i have my accent color set to red in gnome, but the browser keeps the blue accent color. Adding support for the accent color would be very cool.

**Describe your proposed solution**

The app could just edit this ⬇️ bit of the css files in the theme folder to whatever the current accent color is, current accent color could be fetched with the xdg accent color portal spec thingy
```
		/* Accent */
		--gnome-accent-bg: var(--gnome-palette-blue-3);
		--gnome-accent: #78aeed;
```
also, i wanted to add that this app is sick and super underappreciated

**Comment by largestgithubuseronearth** [comment]
The theme dev seems to already have a good solution. Firefox Nightly has accent support and the FGT dev uses that for the theme.
https://github.com/rafaelmardojai/firefox-gnome-theme/commit/8c2d3f66f75fe742f7a2f253dc7d881c4828388e

Firefox Nightly will be stable on 7 January and the theme release will probably come soon after. So it's probably best to wait for that.

Thanks for the suggestion though. Let me know if you have any more questions.

**Comment by largestgithubuseronearth** [comment]
Well I was mistaken. Accent color is now available in FGT v133 :tada:

**Comment by Blisterexe** [comment]
Aawesome! Thank you so much for the quick&informative answers.
