### ISSUE TITLE
[FEATURE REQUEST] display currently installed theme version somewhere

### ISSUE THREAD

**Issue by killarny** [largestgithubuseronearth/addwater#35]
**What is the issue you're having?**
I have poked around and can't find anywhere this is shown in the app dialog right now, but it seems handy to be able to more easily determine which version of the underlying theme is being applied. (Especially in times like when a FF update has broken the theme, and one is eagerly waiting for the theme to be updated.)

Apologies if this is already shown somewhere and I'm too ignorant to have found it. I can't even tell how to see the theme version from within FF, as it just shows the "System theme - auto" is active regardless of whether this one is applied or not. I assume one can find the version by looking at the theme source on disk, but that's less handy than having a nice display somewhere.

**Describe your proposed solution**
Display the theme version somewhere; the about dialog perhaps, or even as a description text on the "Enable Theme" toggle.

**Comment by largestgithubuseronearth** [comment]
That's a good idea. I'll include it in the next update.

At the moment, the only two places the version is stated is in the Firefox "Customize Toolbar" menu and in my logfiles.

**Comment by largestgithubuseronearth** [comment]
The update to v1.2 will come and the theme version will be displayed right on the front.

Thanks for the suggestion!
