### ISSUE TITLE
[KNOWN BUG] Empty GUI / Crash on updating

### ISSUE THREAD

**Issue by largestgithubuseronearth** [largestgithubuseronearth/addwater#43]
After the most recent FGT update, Add Water crashes with an error about the string literal.

This issue will be resolved in the next day or so.

Sorry for any inconvenience this causes.

**Comment by Scotty-Trees** [comment]
I was just about to post this, thanks for the transparency and update. For anyone wondering if it's happening to them too, Water doesn't launch after the most recent update. However, if you go to the top right in Gnome and look for background running apps, water should still show up and you can click on it from there (after it failed to launch of course) and it currently shows an empty screen like shown below:

![Screenshot from 2024-12-12 23-12-59](https://github.com/user-attachments/assets/2f34762b-a919-4d08-9d36-d36c5ae61fe0)

Just documenting that for anyone. Looking forward to the update to fix this. Thanks again!

**Comment by largestgithubuseronearth** [comment]
I've created a fix and am in the process of testing to ensure it causes no new issues when transitioning from the current version of the app. 

If all goes well, the fix will come to Flathub tomorrow.

Thank you all for your patience.

**Comment by largestgithubuseronearth** [comment]
A hotfix to v1.2.1 has been submitted to Flathub and should be available within a few hours. Thank you all for your patience, this was an entirely an oversight on my end.

Please let me know if you encounter any further issues after updating to v1.2.1.

Thanks again

**Comment by yochananmarqos** [comment]
Nope. :disappointed: 

[addwater_2024-12-13.log](https://github.com/user-attachments/files/18132686/addwater_2024-12-13.log)

**Comment by largestgithubuseronearth** [comment]
I see what happened. I sent the git commands in the wrong order so my local repo is different than the Github one.

Apologies. I'll correct that and resend the update.

**Comment by largestgithubuseronearth** [comment]
Okay, resubmitted to Flathub and I triple-checked it this time.

Thanks for letting me know. Sorry again for the delay.

**Comment by yochananmarqos** [comment]
1.2.2 works fine. :+1: 

However, you still have the developer profile option enabled by default instead of user from 1.2.1b1.

**Comment by largestgithubuseronearth** [comment]
> However, you still have the developer profile option enabled by default instead of user from 1.2.1b1.

Where does that occur? I tested the build from Flathub and it has the user profile enabled.

**Comment by yochananmarqos** [comment]
The default profile value in `meson-options` was 'user' for each tag, then it was changed to 'developer' for 1.2.1b1 and was never switched back.

**Comment by largestgithubuseronearth** [comment]
> The default profile value in `meson-options` was 'user' for each tag, then it was changed to 'developer' for 1.2.1b1 and was never switched back.

This option gets overridden at build time by an argument in the Flatpak manifest.

`dev.qwery.AddWater.json` sets it to `user`. This is what Flathub uses.
`dev.qwery.AddWater.Devel.json` sets it to `developer`.

So it doesn't really matter what option is picked in `meson.options`. It's all about which manifest file is used.

**Comment by yochananmarqos** [comment]
Doh! I'm really bad about editing after submitting. :laughing: 

See my above edited comment.

**Comment by largestgithubuseronearth** [comment]
Ah okay. Would it make it easier for you if it was user by default?

**Comment by yochananmarqos** [comment]
Feel free to do whatever works best for you. I can use `-Dprofile=user` while building, that's no problem.

By the way, guess what the Firefox Theme button does in the Manjaro [GNOME Layout Switcher](https://gitlab.manjaro.org/Chrysostomus/gnome-layout-switcher)? :grin: 

![image](https://github.com/user-attachments/assets/554b145e-2ecf-4b3c-a5cc-e4329fc67158)

**Comment by largestgithubuseronearth** [comment]
> By the way, guess what the Firefox Theme button does in the Manjaro [GNOME Layout Switcher](https://gitlab.manjaro.org/Chrysostomus/gnome-layout-switcher)? 😁

Oh that's so cool! I genuinely had no idea it was in AUR. I'm very happy that you've found it helpful :)

**Comment by yochananmarqos** [comment]
Indeed, it is very helpful!

:bow:

**Comment by nickbeth** [comment]
I'm on version 1.2.5 and the same issue is popping up again, even after uninstalling and reinstalling the app through flathub with the Delete data option.

**Comment by largestgithubuseronearth** [comment]
> I'm on version 1.2.5 and the same issue is popping up again, even after uninstalling and reinstalling the app through flathub with the Delete data option.

Sorry to hear that. Please fill out a new issue so we can see investigate further as the cause is probably different than it was in this case. Be sure to include the log file in your new issue. You can save a copy from the menu "About Add Water > Troubleshooting".

Thank you for your patience.
