### ISSUE TITLE
Empty interface at start, does nothing.

### ISSUE THREAD

**Issue by pchmykh** [largestgithubuseronearth/addwater#44]
**Describe the bug**
Empty interface at start, does nothing.

**To Reproduce**
1. Open app
2. App is empty

**Expected behavior**
some controls maybe, not sure, haven't used yet

**Screenshots**
![Screenshot From 2024-12-13 16-48-50](https://github.com/user-attachments/assets/493e4d54-8914-4f39-86b1-d45eec3e287c)

**Technical Details (please complete the following information):**
```
 - Distribution: Fedora Linux 41 (Workstation Edition)
 - Add Water version: 1.2

 - Browser: Firefox
 - Browser Package: Flatpak
 - Browser Version: 133.0.3
```

**Additional context**

**Attach log file if necessary**
[addwater_2024-12-13.log](https://github.com/user-attachments/files/18127141/addwater_2024-12-13.log)

**Comment by largestgithubuseronearth** [comment]
I am aware of the issue. A hotfix will be sent soon. See #43 

Sorry about the inconvenience.
