### ISSUE TITLE
[BUG] App launches into empty interface

### ISSUE THREAD

**Issue by timoteosg** [largestgithubuseronearth/addwater#45]
**Describe the bug**
Whenever I open the app, it opens to the interface being empty. I just get the top bar with the menu buttons.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Add Water

**Expected behavior**
UI to load

**Screenshots**
![grafik](https://github.com/user-attachments/assets/4529bc56-d110-4bec-80f2-6f2fa1ea69f5)

**Technical Details:**
```
 - Distribution: Fedora Linux 41 (Workstation Edition) x86_64
 - Add Water version: 1.2
 - Browser: Firefox
 - Browser Package: RPM
 - Browser Version: 133.0
```

**Additional context**
I tried opening it with and without graphics drivers, to no avail. It previously worked for me on Fedora 40.

**Attach log file if necessary**
[addwater_2024-12-13.log](https://github.com/user-attachments/files/18130834/addwater_2024-12-13.log)

**Comment by largestgithubuseronearth** [comment]
I am aware of the issue. A hotfix will be sent soon. See #43 

Sorry about the inconvenience.

**Comment by timoteosg** [comment]
> I am aware of the issue. A hotfix will be sent soon. See #43
> 
> Sorry about the inconvenience.

Very kind, thank you!!
